Mode: 1
ProtoFolder: "../pb"
FromDatabase:
  UserName: "db_user"
  Password: "password"
  Server: "192.168.0.41"
  Port: 3306
  Name: "pekomiko"
FromTable: "Account"
ToDatabase:
  UserName: "db_user"
  Password: "password"
  Server: "192.168.0.41"
  Port: 3306
  Name: "pekomiko"
ToTable: "Account"
Generate: true
Print: false
Sync: true