// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.4
// source: pb/_mail_user.proto

package pbgo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// {"index": [{"name": "索引 1", "columns": ["to_uid", "expiry_time", "del_fl"]}]}
type XMailUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// {"comment": "郵件 id", "type": "BIGINT", "size": 20, "default": "ai", "can_null": "false"}
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// {"comment": "系統郵件 id", "type": "BIGINT", "size": 20, "default": "0", "can_null": "false"}
	SystemId int64 `protobuf:"varint,2,opt,name=system_id,json=systemId,proto3" json:"system_id,omitempty"`
	// {"comment": "發信玩家id (-1表示系統郵件)", "type": "BIGINT", "size": 20, "default": "0", "can_null": "false"}
	FromUid int64 `protobuf:"varint,3,opt,name=from_uid,json=fromUid,proto3" json:"from_uid,omitempty"`
	// {"comment": "收信玩家id (-1表示全部)", "type": "BIGINT", "size": 20, "default": "0", "can_null": "false"}
	ToUid int64 `protobuf:"varint,4,opt,name=to_uid,json=toUid,proto3" json:"to_uid,omitempty"`
	// {"comment": "標題", "type": "VARCHAR", "size": 40, "default": "'無標題'", "can_null": "false"}
	Title string `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	// {"comment": "信件內容", "type": "VARCHAR", "size": 1024, "default": "''", "can_null": "false"}
	Content string `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	// {"comment": "夾帶的道具列表", "type": "VARCHAR", "size": 128, "default": "''", "can_null": "false"}
	ItemList string `protobuf:"bytes,7,opt,name=item_list,json=itemList,proto3" json:"item_list,omitempty"`
	// {"comment": "夾帶的金幣值", "type": "INT", "size": 11, "default": "0", "can_null": "true"}
	Gold_0 int32 `protobuf:"varint,8,opt,name=gold_0,json=gold0,proto3" json:"gold_0,omitempty"`
	// {"comment": "夾帶的寶石", "type": "INT", "size": 11, "default": "0", "can_null": "true"}
	Gold_1 int32 `protobuf:"varint,9,opt,name=gold_1,json=gold1,proto3" json:"gold_1,omitempty"`
	// {"comment": "依遊戲定義", "type": "INT", "size": 11, "default": "0", "can_null": "true"}
	Gold_2 int32 `protobuf:"varint,10,opt,name=gold_2,json=gold2,proto3" json:"gold_2,omitempty"`
	// {"comment": "依遊戲定義", "type": "INT", "size": 11, "default": "0", "can_null": "true"}
	Gold_3 int32 `protobuf:"varint,11,opt,name=gold_3,json=gold3,proto3" json:"gold_3,omitempty"`
	// {"comment": "建立時間", "type": "TIMESTAMP", "default": "current_timestamp()", "can_null": "false"}
	CreateTime *TimeStamp `protobuf:"bytes,12,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// {"comment": "郵件的有效期限", "type": "TIMESTAMP", "default": "current_timestamp()", "can_null": "false"}
	ExpiryTime *TimeStamp `protobuf:"bytes,13,opt,name=expiry_time,json=expiryTime,proto3" json:"expiry_time,omitempty"`
	// {"comment": "刪除旗號", "type": "TINYINT", "size": 4, "default": "0", "can_null": "false"}
	DelFl int32 `protobuf:"varint,14,opt,name=del_fl,json=delFl,proto3" json:"del_fl,omitempty"`
	// {"comment": "是否已讀", "type": "TINYINT", "size": 4, "default": "0", "can_null": "false"}
	ReadFl int32 `protobuf:"varint,15,opt,name=read_fl,json=readFl,proto3" json:"read_fl,omitempty"`
	// {"comment": "是否已領取道具", "type": "TINYINT", "size": 4, "default": "0", "can_null": "false"}
	GetFl int32 `protobuf:"varint,16,opt,name=get_fl,json=getFl,proto3" json:"get_fl,omitempty"`
	// {"comment": "最後一次的更新時間", "type": "TIMESTAMP", "can_null": "false"}
	// {"default": "current_timestamp()", "update": "current_timestamp()"}
	LastUpdateTime *TimeStamp `protobuf:"bytes,17,opt,name=last_update_time,json=lastUpdateTime,proto3" json:"last_update_time,omitempty"`
}

func (x *XMailUser) Reset() {
	*x = XMailUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb__mail_user_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XMailUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XMailUser) ProtoMessage() {}

func (x *XMailUser) ProtoReflect() protoreflect.Message {
	mi := &file_pb__mail_user_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XMailUser.ProtoReflect.Descriptor instead.
func (*XMailUser) Descriptor() ([]byte, []int) {
	return file_pb__mail_user_proto_rawDescGZIP(), []int{0}
}

func (x *XMailUser) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *XMailUser) GetSystemId() int64 {
	if x != nil {
		return x.SystemId
	}
	return 0
}

func (x *XMailUser) GetFromUid() int64 {
	if x != nil {
		return x.FromUid
	}
	return 0
}

func (x *XMailUser) GetToUid() int64 {
	if x != nil {
		return x.ToUid
	}
	return 0
}

func (x *XMailUser) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *XMailUser) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *XMailUser) GetItemList() string {
	if x != nil {
		return x.ItemList
	}
	return ""
}

func (x *XMailUser) GetGold_0() int32 {
	if x != nil {
		return x.Gold_0
	}
	return 0
}

func (x *XMailUser) GetGold_1() int32 {
	if x != nil {
		return x.Gold_1
	}
	return 0
}

func (x *XMailUser) GetGold_2() int32 {
	if x != nil {
		return x.Gold_2
	}
	return 0
}

func (x *XMailUser) GetGold_3() int32 {
	if x != nil {
		return x.Gold_3
	}
	return 0
}

func (x *XMailUser) GetCreateTime() *TimeStamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *XMailUser) GetExpiryTime() *TimeStamp {
	if x != nil {
		return x.ExpiryTime
	}
	return nil
}

func (x *XMailUser) GetDelFl() int32 {
	if x != nil {
		return x.DelFl
	}
	return 0
}

func (x *XMailUser) GetReadFl() int32 {
	if x != nil {
		return x.ReadFl
	}
	return 0
}

func (x *XMailUser) GetGetFl() int32 {
	if x != nil {
		return x.GetFl
	}
	return 0
}

func (x *XMailUser) GetLastUpdateTime() *TimeStamp {
	if x != nil {
		return x.LastUpdateTime
	}
	return nil
}

var File_pb__mail_user_proto protoreflect.FileDescriptor

var file_pb__mail_user_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x62, 0x2f, 0x5f, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x70, 0x62, 0x2f, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xeb, 0x03, 0x0a, 0x0a, 0x5f, 0x6d,
	0x61, 0x69, 0x6c, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x79, 0x73, 0x74,
	0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x79, 0x73,
	0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x75, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x66, 0x72, 0x6f, 0x6d, 0x55, 0x69, 0x64,
	0x12, 0x15, 0x0a, 0x06, 0x74, 0x6f, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x74, 0x6f, 0x55, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x74, 0x65, 0x6d, 0x5f,
	0x6c, 0x69, 0x73, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x74, 0x65, 0x6d,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x67, 0x6f, 0x6c, 0x64, 0x5f, 0x30, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x67, 0x6f, 0x6c, 0x64, 0x30, 0x12, 0x15, 0x0a, 0x06, 0x67,
	0x6f, 0x6c, 0x64, 0x5f, 0x31, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x67, 0x6f, 0x6c,
	0x64, 0x31, 0x12, 0x15, 0x0a, 0x06, 0x67, 0x6f, 0x6c, 0x64, 0x5f, 0x32, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x67, 0x6f, 0x6c, 0x64, 0x32, 0x12, 0x15, 0x0a, 0x06, 0x67, 0x6f, 0x6c,
	0x64, 0x5f, 0x33, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x67, 0x6f, 0x6c, 0x64, 0x33,
	0x12, 0x2b, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x2b, 0x0a,
	0x0b, 0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x0d, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a,
	0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x64, 0x65,
	0x6c, 0x5f, 0x66, 0x6c, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x64, 0x65, 0x6c, 0x46,
	0x6c, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x65, 0x61, 0x64, 0x5f, 0x66, 0x6c, 0x18, 0x0f, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x61, 0x64, 0x46, 0x6c, 0x12, 0x15, 0x0a, 0x06, 0x67, 0x65,
	0x74, 0x5f, 0x66, 0x6c, 0x18, 0x10, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x67, 0x65, 0x74, 0x46,
	0x6c, 0x12, 0x34, 0x0a, 0x10, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x11, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0e, 0x6c, 0x61, 0x73, 0x74, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x3b, 0x70, 0x62, 0x67,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb__mail_user_proto_rawDescOnce sync.Once
	file_pb__mail_user_proto_rawDescData = file_pb__mail_user_proto_rawDesc
)

func file_pb__mail_user_proto_rawDescGZIP() []byte {
	file_pb__mail_user_proto_rawDescOnce.Do(func() {
		file_pb__mail_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb__mail_user_proto_rawDescData)
	})
	return file_pb__mail_user_proto_rawDescData
}

var file_pb__mail_user_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pb__mail_user_proto_goTypes = []interface{}{
	(*XMailUser)(nil), // 0: _mail_user
	(*TimeStamp)(nil), // 1: TimeStamp
}
var file_pb__mail_user_proto_depIdxs = []int32{
	1, // 0: _mail_user.create_time:type_name -> TimeStamp
	1, // 1: _mail_user.expiry_time:type_name -> TimeStamp
	1, // 2: _mail_user.last_update_time:type_name -> TimeStamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pb__mail_user_proto_init() }
func file_pb__mail_user_proto_init() {
	if File_pb__mail_user_proto != nil {
		return
	}
	file_pb_TimeStamp_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_pb__mail_user_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XMailUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb__mail_user_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb__mail_user_proto_goTypes,
		DependencyIndexes: file_pb__mail_user_proto_depIdxs,
		MessageInfos:      file_pb__mail_user_proto_msgTypes,
	}.Build()
	File_pb__mail_user_proto = out.File
	file_pb__mail_user_proto_rawDesc = nil
	file_pb__mail_user_proto_goTypes = nil
	file_pb__mail_user_proto_depIdxs = nil
}
