// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.4
// source: pb/account.proto

package pbgo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// {"unique": [{"name": "guest_idx", "columns": ["game_code", "account_guest"]}]}
// {"unique": [{"name": "google_idx", "columns": ["game_code", "account_google"]}]}
// {"unique": [{"name": "apple_idx", "columns": ["game_code", "account_apple"]}]}
// {"unique": [{"name": "fb_idx", "columns": ["game_code", "account_fb"]}]}
type Account struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// {"comment": "玩家 ID", "type": "BIGINT", "size": 20, "default": "ai", "can_null": "false"}
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// {"comment": "隨機亂數(和 uid 搭配可以避免玩家亂認帳號)"}
	// {"type": "INT", "size": 11, "default": "null", "can_null": "true"}
	UidRand int32 `protobuf:"varint,2,opt,name=uid_rand,json=uidRand,proto3" json:"uid_rand,omitempty"`
	// {"comment": "遊戲編號", "type": "BIGINT", "size": 20, "default": "-1", "can_null": "false"}
	GameCode int32 `protobuf:"varint,3,opt,name=game_code,json=gameCode,proto3" json:"game_code,omitempty"`
	// {"comment": "app 來源渠道 ID", "type": "INT", "size": 11, "default": "-1", "can_null": "false"}
	AppSourceId int32 `protobuf:"varint,4,opt,name=app_source_id,json=appSourceId,proto3" json:"app_source_id,omitempty"`
	// {"comment": "app 的版號", "type": "TINYTEXT", "default": "nil", "can_null": "false"}
	AppVer string `protobuf:"bytes,5,opt,name=app_ver,json=appVer,proto3" json:"app_ver,omitempty"`
	// {"comment": "玩家設備的OS(-1=不明來源，0=PC，1=Android，2=iOS，99=其他平台)"}
	// {"type": "TINYINT", "size": 4, "default": "-1", "can_null": "false"}
	DeviceOsType int32 `protobuf:"varint,6,opt,name=device_os_type,json=deviceOsType,proto3" json:"device_os_type,omitempty"`
	// {"comment": "參觀帳號(純英文)", "type": "VARCHAR", "size": 128, "default": "null", "can_null": "true"}
	AccountGuest string `protobuf:"bytes,7,opt,name=account_guest,json=accountGuest,proto3" json:"account_guest,omitempty"`
	// {"comment": "Google帳號(純英文)", "type": "VARCHAR", "size": 128, "default": "null", "can_null": "true"}
	AccountGoogle string `protobuf:"bytes,8,opt,name=account_google,json=accountGoogle,proto3" json:"account_google,omitempty"`
	// {"comment": "Apple帳號(純英文)", "type": "VARCHAR", "size": 128, "default": "null", "can_null": "true"}
	AccountApple string `protobuf:"bytes,9,opt,name=account_apple,json=accountApple,proto3" json:"account_apple,omitempty"`
	// {"comment": "fb帳號(純英文)", "type": "VARCHAR", "size": 128, "default": "null", "can_null": "true"}
	AccountFb string `protobuf:"bytes,10,opt,name=account_fb,json=accountFb,proto3" json:"account_fb,omitempty"`
	// {"comment": "暱稱(可中文)", "type": "VARCHAR", "size": 20, "default": "null", "can_null": "true"}
	Nickname string `protobuf:"bytes,11,opt,name=nickname,proto3" json:"nickname,omitempty"`
	// {"comment": "信箱(純英文)", "type": "VARCHAR", "size": 256, "default": "''", "can_null": "false"}
	Email string `protobuf:"bytes,12,opt,name=email,proto3" json:"email,omitempty"`
	// {"comment": "帳號建立時間", "type": "TIMESTAMP", "default": "current_timestamp()", "can_null": "false"}
	CreateTime *TimeStamp `protobuf:"bytes,13,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// {"comment": "最後一次的更新時間", "type": "TIMESTAMP", "can_null": "false"}
	// {"default": "current_timestamp()", "update": "current_timestamp()"}
	LastUpdateTime *TimeStamp `protobuf:"bytes,14,opt,name=last_update_time,json=lastUpdateTime,proto3" json:"last_update_time,omitempty"`
	// {"comment": "會員等級", "type": "TINYINT", "size": 4, "default": "0", "can_null": "false"}
	VipLv int32 `protobuf:"varint,15,opt,name=vip_lv,json=vipLv,proto3" json:"vip_lv,omitempty"`
	// {"comment": "貢獻值", "type": "BIGINT", "size": 20, "default": "0", "can_null": "false"}
	Contribute int64 `protobuf:"varint,16,opt,name=contribute,proto3" json:"contribute,omitempty"`
	// {"comment": "GM 旗號", "type": "INT", "size": 11, "default": "0", "can_null": "false"}
	GmFl int32 `protobuf:"varint,17,opt,name=gm_fl,json=gmFl,proto3" json:"gm_fl,omitempty"`
}

func (x *Account) Reset() {
	*x = Account{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_account_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_pb_account_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_pb_account_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Account) GetUidRand() int32 {
	if x != nil {
		return x.UidRand
	}
	return 0
}

func (x *Account) GetGameCode() int32 {
	if x != nil {
		return x.GameCode
	}
	return 0
}

func (x *Account) GetAppSourceId() int32 {
	if x != nil {
		return x.AppSourceId
	}
	return 0
}

func (x *Account) GetAppVer() string {
	if x != nil {
		return x.AppVer
	}
	return ""
}

func (x *Account) GetDeviceOsType() int32 {
	if x != nil {
		return x.DeviceOsType
	}
	return 0
}

func (x *Account) GetAccountGuest() string {
	if x != nil {
		return x.AccountGuest
	}
	return ""
}

func (x *Account) GetAccountGoogle() string {
	if x != nil {
		return x.AccountGoogle
	}
	return ""
}

func (x *Account) GetAccountApple() string {
	if x != nil {
		return x.AccountApple
	}
	return ""
}

func (x *Account) GetAccountFb() string {
	if x != nil {
		return x.AccountFb
	}
	return ""
}

func (x *Account) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *Account) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Account) GetCreateTime() *TimeStamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Account) GetLastUpdateTime() *TimeStamp {
	if x != nil {
		return x.LastUpdateTime
	}
	return nil
}

func (x *Account) GetVipLv() int32 {
	if x != nil {
		return x.VipLv
	}
	return 0
}

func (x *Account) GetContribute() int64 {
	if x != nil {
		return x.Contribute
	}
	return 0
}

func (x *Account) GetGmFl() int32 {
	if x != nil {
		return x.GmFl
	}
	return 0
}

var File_pb_account_proto protoreflect.FileDescriptor

var file_pb_account_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x62, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x12, 0x70, 0x62, 0x2f, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa5, 0x04, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x75, 0x69, 0x64, 0x5f, 0x72, 0x61, 0x6e, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x75, 0x69, 0x64, 0x52, 0x61, 0x6e, 0x64, 0x12, 0x1b, 0x0a,
	0x09, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x22, 0x0a, 0x0d, 0x61, 0x70,
	0x70, 0x5f, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0b, 0x61, 0x70, 0x70, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x64, 0x12, 0x17,
	0x0a, 0x07, 0x61, 0x70, 0x70, 0x5f, 0x76, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x61, 0x70, 0x70, 0x56, 0x65, 0x72, 0x12, 0x24, 0x0a, 0x0e, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x5f, 0x6f, 0x73, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0c, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x23, 0x0a,
	0x0d, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x67, 0x75, 0x65, 0x73, 0x74, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x47, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x61, 0x70, 0x70, 0x6c, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x70, 0x70, 0x6c, 0x65, 0x12, 0x1d,
	0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x66, 0x62, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x46, 0x62, 0x12, 0x1a, 0x0a,
	0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12,
	0x2b, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x0d,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x34, 0x0a, 0x10,
	0x6c, 0x61, 0x73, 0x74, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x0e, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x0e, 0x6c, 0x61, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x76, 0x69, 0x70, 0x5f, 0x6c, 0x76, 0x18, 0x0f, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x76, 0x69, 0x70, 0x4c, 0x76, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6e,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x18, 0x10, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x12, 0x13, 0x0a, 0x05, 0x67, 0x6d, 0x5f,
	0x66, 0x6c, 0x18, 0x11, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x67, 0x6d, 0x46, 0x6c, 0x42, 0x08,
	0x5a, 0x06, 0x2e, 0x3b, 0x70, 0x62, 0x67, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_account_proto_rawDescOnce sync.Once
	file_pb_account_proto_rawDescData = file_pb_account_proto_rawDesc
)

func file_pb_account_proto_rawDescGZIP() []byte {
	file_pb_account_proto_rawDescOnce.Do(func() {
		file_pb_account_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_account_proto_rawDescData)
	})
	return file_pb_account_proto_rawDescData
}

var file_pb_account_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pb_account_proto_goTypes = []interface{}{
	(*Account)(nil),   // 0: account
	(*TimeStamp)(nil), // 1: TimeStamp
}
var file_pb_account_proto_depIdxs = []int32{
	1, // 0: account.create_time:type_name -> TimeStamp
	1, // 1: account.last_update_time:type_name -> TimeStamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pb_account_proto_init() }
func file_pb_account_proto_init() {
	if File_pb_account_proto != nil {
		return
	}
	file_pb_TimeStamp_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_pb_account_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Account); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_account_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_account_proto_goTypes,
		DependencyIndexes: file_pb_account_proto_depIdxs,
		MessageInfos:      file_pb_account_proto_msgTypes,
	}.Build()
	File_pb_account_proto = out.File
	file_pb_account_proto_rawDesc = nil
	file_pb_account_proto_goTypes = nil
	file_pb_account_proto_depIdxs = nil
}
