// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.4
// source: pb/AllMight.proto

package pbgo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 編譯：執行 compile_protobuf.bat
type AllMight struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// {"comment": "BIGINT", "type":"BIGINT", "size": 20, "primary_key": "default"}
	Bi int64 `protobuf:"varint,1,opt,name=bi,proto3" json:"bi,omitempty"`
	// {"comment": "bool 的 size 應為 1", "type":"TINYINT"}
	B bool `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
	// {"comment": "TINYINT", "type":"TINYINT", "size": 4}
	Ti int32 `protobuf:"varint,3,opt,name=ti,proto3" json:"ti,omitempty"`
	// {"comment": "SMALINT", "type":"SMALINT", "size": 6}
	Si int32 `protobuf:"varint,4,opt,name=si,proto3" json:"si,omitempty"`
	// {"comment": "MEDIUMINT", "type":"MEDIUMINT", "size": 9}
	Mi int32 `protobuf:"varint,5,opt,name=mi,proto3" json:"mi,omitempty"`
	// {"comment": "INT", "type":"INT", "size": 11}
	I int32 `protobuf:"varint,6,opt,name=i,proto3" json:"i,omitempty"`
	// {"comment": "TINYTEXT", "type":"TINYTEXT"}
	Tt string `protobuf:"bytes,7,opt,name=tt,proto3" json:"tt,omitempty"`
	// {"comment": "VARCHAR", "type":"VARCHAR", "size":3000}
	Vc string `protobuf:"bytes,8,opt,name=vc,proto3" json:"vc,omitempty"`
	// {"comment": "TEXT", "type":"TEXT"}
	T string `protobuf:"bytes,9,opt,name=t,proto3" json:"t,omitempty"`
	// {"comment": "MEDIUMTEXT", "type":"MEDIUMTEXT"}
	Mt string `protobuf:"bytes,10,opt,name=mt,proto3" json:"mt,omitempty"`
	// {"comment": "LONGTEXT", "type":"LONGTEXT"}
	Lt string `protobuf:"bytes,11,opt,name=lt,proto3" json:"lt,omitempty"`
	// {"comment": "TIMESTAMP", "type":"TIMESTAMP", "default":"current_timestamp()", "update":"current_timestamp()"}
	Ts *TimeStamp `protobuf:"bytes,12,opt,name=ts,proto3" json:"ts,omitempty"`
}

func (x *AllMight) Reset() {
	*x = AllMight{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_AllMight_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllMight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllMight) ProtoMessage() {}

func (x *AllMight) ProtoReflect() protoreflect.Message {
	mi := &file_pb_AllMight_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllMight.ProtoReflect.Descriptor instead.
func (*AllMight) Descriptor() ([]byte, []int) {
	return file_pb_AllMight_proto_rawDescGZIP(), []int{0}
}

func (x *AllMight) GetBi() int64 {
	if x != nil {
		return x.Bi
	}
	return 0
}

func (x *AllMight) GetB() bool {
	if x != nil {
		return x.B
	}
	return false
}

func (x *AllMight) GetTi() int32 {
	if x != nil {
		return x.Ti
	}
	return 0
}

func (x *AllMight) GetSi() int32 {
	if x != nil {
		return x.Si
	}
	return 0
}

func (x *AllMight) GetMi() int32 {
	if x != nil {
		return x.Mi
	}
	return 0
}

func (x *AllMight) GetI() int32 {
	if x != nil {
		return x.I
	}
	return 0
}

func (x *AllMight) GetTt() string {
	if x != nil {
		return x.Tt
	}
	return ""
}

func (x *AllMight) GetVc() string {
	if x != nil {
		return x.Vc
	}
	return ""
}

func (x *AllMight) GetT() string {
	if x != nil {
		return x.T
	}
	return ""
}

func (x *AllMight) GetMt() string {
	if x != nil {
		return x.Mt
	}
	return ""
}

func (x *AllMight) GetLt() string {
	if x != nil {
		return x.Lt
	}
	return ""
}

func (x *AllMight) GetTs() *TimeStamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

var File_pb_AllMight_proto protoreflect.FileDescriptor

var file_pb_AllMight_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x62, 0x2f, 0x41, 0x6c, 0x6c, 0x4d, 0x69, 0x67, 0x68, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x70, 0x62, 0x2f, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd0, 0x01, 0x0a, 0x08, 0x41, 0x6c, 0x6c, 0x4d,
	0x69, 0x67, 0x68, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x62, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x62, 0x69, 0x12, 0x0c, 0x0a, 0x01, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x01, 0x62, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x69, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x74, 0x69, 0x12, 0x0e, 0x0a, 0x02, 0x73, 0x69, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x73, 0x69, 0x12, 0x0e, 0x0a, 0x02, 0x6d, 0x69, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x6d, 0x69, 0x12, 0x0c, 0x0a, 0x01, 0x69, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x69,
	0x12, 0x0e, 0x0a, 0x02, 0x74, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x76, 0x63, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x76, 0x63,
	0x12, 0x0c, 0x0a, 0x01, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x6d, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6d, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x6c, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6c, 0x74, 0x12, 0x1a,
	0x0a, 0x02, 0x74, 0x73, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x3b,
	0x70, 0x62, 0x67, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_AllMight_proto_rawDescOnce sync.Once
	file_pb_AllMight_proto_rawDescData = file_pb_AllMight_proto_rawDesc
)

func file_pb_AllMight_proto_rawDescGZIP() []byte {
	file_pb_AllMight_proto_rawDescOnce.Do(func() {
		file_pb_AllMight_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_AllMight_proto_rawDescData)
	})
	return file_pb_AllMight_proto_rawDescData
}

var file_pb_AllMight_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pb_AllMight_proto_goTypes = []interface{}{
	(*AllMight)(nil),  // 0: AllMight
	(*TimeStamp)(nil), // 1: TimeStamp
}
var file_pb_AllMight_proto_depIdxs = []int32{
	1, // 0: AllMight.ts:type_name -> TimeStamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pb_AllMight_proto_init() }
func file_pb_AllMight_proto_init() {
	if File_pb_AllMight_proto != nil {
		return
	}
	file_pb_TimeStamp_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_pb_AllMight_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllMight); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_AllMight_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_AllMight_proto_goTypes,
		DependencyIndexes: file_pb_AllMight_proto_depIdxs,
		MessageInfos:      file_pb_AllMight_proto_msgTypes,
	}.Build()
	File_pb_AllMight_proto = out.File
	file_pb_AllMight_proto_rawDesc = nil
	file_pb_AllMight_proto_goTypes = nil
	file_pb_AllMight_proto_depIdxs = nil
}
