// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.4
// source: pb/api_log.proto

package pbgo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// {"index": [{"name": "索引 1", "columns": ["create_time", "uid"]}]}
// {"index": [{"name": "索引 2", "columns": ["create_time", "api_type"]}]}
// {"index": [{"name": "索引 3", "columns": ["create_time", "ret"]}]}
type ApiLog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// {"comment": "玩家 ID", "type": "BIGINT", "size": 20, "default": "nil", "can_null": "false"}
	Uid int64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// {"comment": "通行口令", "type": "BIGINT", "size": 20, "default": "nil", "can_null": "false"}
	Token int64 `protobuf:"varint,2,opt,name=token,proto3" json:"token,omitempty"`
	// {"comment": "叫用的 api 名稱", "type": "INT", "size": 11, "default": "nil", "can_null": "false"}
	ApiType int32 `protobuf:"varint,3,opt,name=api_type,json=apiType,proto3" json:"api_type,omitempty"`
	// {"comment": "錯誤碼", "type": "INT", "size": 11, "default": "nil", "can_null": "false"}
	Ret int32 `protobuf:"varint,4,opt,name=ret,proto3" json:"ret,omitempty"`
	// {"comment": "寶石", "type": "TEXT", "default": "''", "can_null": "false"}
	Msg string `protobuf:"bytes,5,opt,name=msg,proto3" json:"msg,omitempty"`
	// {"comment": "帳號建立時間", "type": "TIMESTAMP", "default": "current_timestamp()", "can_null": "false"}
	CreateTime *TimeStamp `protobuf:"bytes,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
}

func (x *ApiLog) Reset() {
	*x = ApiLog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_api_log_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApiLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiLog) ProtoMessage() {}

func (x *ApiLog) ProtoReflect() protoreflect.Message {
	mi := &file_pb_api_log_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiLog.ProtoReflect.Descriptor instead.
func (*ApiLog) Descriptor() ([]byte, []int) {
	return file_pb_api_log_proto_rawDescGZIP(), []int{0}
}

func (x *ApiLog) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ApiLog) GetToken() int64 {
	if x != nil {
		return x.Token
	}
	return 0
}

func (x *ApiLog) GetApiType() int32 {
	if x != nil {
		return x.ApiType
	}
	return 0
}

func (x *ApiLog) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *ApiLog) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ApiLog) GetCreateTime() *TimeStamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

var File_pb_api_log_proto protoreflect.FileDescriptor

var file_pb_api_log_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x62, 0x2f, 0x61, 0x70, 0x69, 0x5f, 0x6c, 0x6f, 0x67, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x12, 0x70, 0x62, 0x2f, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9d, 0x01, 0x0a, 0x07, 0x61, 0x70, 0x69, 0x5f, 0x6c,
	0x6f, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x03, 0x75, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x70,
	0x69, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x61, 0x70,
	0x69, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x2b, 0x0a, 0x0b, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x3b, 0x70, 0x62, 0x67, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_api_log_proto_rawDescOnce sync.Once
	file_pb_api_log_proto_rawDescData = file_pb_api_log_proto_rawDesc
)

func file_pb_api_log_proto_rawDescGZIP() []byte {
	file_pb_api_log_proto_rawDescOnce.Do(func() {
		file_pb_api_log_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_api_log_proto_rawDescData)
	})
	return file_pb_api_log_proto_rawDescData
}

var file_pb_api_log_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pb_api_log_proto_goTypes = []interface{}{
	(*ApiLog)(nil),    // 0: api_log
	(*TimeStamp)(nil), // 1: TimeStamp
}
var file_pb_api_log_proto_depIdxs = []int32{
	1, // 0: api_log.create_time:type_name -> TimeStamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pb_api_log_proto_init() }
func file_pb_api_log_proto_init() {
	if File_pb_api_log_proto != nil {
		return
	}
	file_pb_TimeStamp_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_pb_api_log_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApiLog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_api_log_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_api_log_proto_goTypes,
		DependencyIndexes: file_pb_api_log_proto_depIdxs,
		MessageInfos:      file_pb_api_log_proto_msgTypes,
	}.Build()
	File_pb_api_log_proto = out.File
	file_pb_api_log_proto_rawDesc = nil
	file_pb_api_log_proto_goTypes = nil
	file_pb_api_log_proto_depIdxs = nil
}
