// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.4
// source: pb/common_log.proto

package pbgo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// {"index": [{"name": "索引 2", "columns": ["env_type", "game_code", "create_time", "uid"]}]}
type CommonLog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// {"comment": "流水編號", "type": "BIGINT", "size": 20, "default": "ai", "primary_key": "default"}
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// {"comment": "環境類別", "type": "TINYINT", "size": 4, "default": "nil", "can_null": "false"}
	EnvType int32 `protobuf:"varint,2,opt,name=env_type,json=envType,proto3" json:"env_type,omitempty"`
	// {"comment": "遊戲編號", "type": "SMALLINT", "size": 6, "default": "nil", "can_null": "false"}
	GameCode int32 `protobuf:"varint,3,opt,name=game_code,json=gameCode,proto3" json:"game_code,omitempty"`
	// {"comment": "打點分類", "type": "SMALLINT", "size": 6, "default": "nil", "can_null": "false"}
	BiType int32 `protobuf:"varint,4,opt,name=bi_type,json=biType,proto3" json:"bi_type,omitempty"`
	// {"comment": "-1=未知，0=PC，1=Android，2=iOS"}
	// {"type": "TINYINT", "size": 4, "default": "-1", "can_null": "false"}
	AppType int32 `protobuf:"varint,5,opt,name=app_type,json=appType,proto3" json:"app_type,omitempty"`
	// {"comment": "玩家 ID", "type": "BIGINT", "size": 20, "default": "-1", "can_null": "false"}
	Uid int32 `protobuf:"varint,6,opt,name=uid,proto3" json:"uid,omitempty"`
	// {"comment": "資料 1", "type": "INT", "size": 11, "default": "0", "can_null": "false"}
	Data_1 int32 `protobuf:"varint,7,opt,name=data_1,json=data1,proto3" json:"data_1,omitempty"`
	// {"comment": "資料 2", "type": "INT", "size": 11, "default": "0", "can_null": "false"}
	Data_2 int32 `protobuf:"varint,8,opt,name=data_2,json=data2,proto3" json:"data_2,omitempty"`
	// {"comment": "資料 10", "type": "DOUBLE", "default": "0", "can_null": "false"}
	Data_10 float64 `protobuf:"fixed64,9,opt,name=data_10,json=data10,proto3" json:"data_10,omitempty"`
	// {"comment": "資料 20", "type": "TEXT", "default": "'0'", "can_null": "true"}
	Data_20 string `protobuf:"bytes,10,opt,name=data_20,json=data20,proto3" json:"data_20,omitempty"`
	// {"comment": "Log 建立時間", "type": "TIMESTAMP", "default": "current_timestamp()", "can_null": "false"}
	CreateTime *TimeStamp `protobuf:"bytes,11,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// {"comment": "字串 0", "type": "MEDIUMTEXT", "size": 4, "default": "''", "can_null": "false"}
	D_0 string `protobuf:"bytes,12,opt,name=d_0,json=d0,proto3" json:"d_0,omitempty"`
	// {"comment": "字串 1", "type": "MEDIUMTEXT", "size": 4, "default": "''", "can_null": "false"}
	D_1 string `protobuf:"bytes,13,opt,name=d_1,json=d1,proto3" json:"d_1,omitempty"`
	// {"comment": "字串 2", "type": "MEDIUMTEXT", "size": 4, "default": "''", "can_null": "false"}
	D_2 string `protobuf:"bytes,14,opt,name=d_2,json=d2,proto3" json:"d_2,omitempty"`
	// {"comment": "字串 3", "type": "MEDIUMTEXT", "size": 4, "default": "''", "can_null": "false"}
	D_3 string `protobuf:"bytes,15,opt,name=d_3,json=d3,proto3" json:"d_3,omitempty"`
	// {"comment": "字串 4", "type": "MEDIUMTEXT", "size": 4, "default": "''", "can_null": "false"}
	D_4 string `protobuf:"bytes,16,opt,name=d_4,json=d4,proto3" json:"d_4,omitempty"`
	// {"comment": "字串 5", "type": "MEDIUMTEXT", "size": 4, "default": "''", "can_null": "false"}
	D_5 string `protobuf:"bytes,17,opt,name=d_5,json=d5,proto3" json:"d_5,omitempty"`
	// {"comment": "字串 6", "type": "MEDIUMTEXT", "size": 4, "default": "''", "can_null": "false"}
	D_6 string `protobuf:"bytes,18,opt,name=d_6,json=d6,proto3" json:"d_6,omitempty"`
	// {"comment": "字串 7", "type": "MEDIUMTEXT", "size": 4, "default": "''", "can_null": "false"}
	D_7 string `protobuf:"bytes,19,opt,name=d_7,json=d7,proto3" json:"d_7,omitempty"`
	// {"comment": "字串 8", "type": "MEDIUMTEXT", "size": 4, "default": "''", "can_null": "false"}
	D_8 string `protobuf:"bytes,20,opt,name=d_8,json=d8,proto3" json:"d_8,omitempty"`
	// {"comment": "字串 9", "type": "MEDIUMTEXT", "size": 4, "default": "''", "can_null": "false"}
	D_9 string `protobuf:"bytes,21,opt,name=d_9,json=d9,proto3" json:"d_9,omitempty"`
}

func (x *CommonLog) Reset() {
	*x = CommonLog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_common_log_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonLog) ProtoMessage() {}

func (x *CommonLog) ProtoReflect() protoreflect.Message {
	mi := &file_pb_common_log_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonLog.ProtoReflect.Descriptor instead.
func (*CommonLog) Descriptor() ([]byte, []int) {
	return file_pb_common_log_proto_rawDescGZIP(), []int{0}
}

func (x *CommonLog) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CommonLog) GetEnvType() int32 {
	if x != nil {
		return x.EnvType
	}
	return 0
}

func (x *CommonLog) GetGameCode() int32 {
	if x != nil {
		return x.GameCode
	}
	return 0
}

func (x *CommonLog) GetBiType() int32 {
	if x != nil {
		return x.BiType
	}
	return 0
}

func (x *CommonLog) GetAppType() int32 {
	if x != nil {
		return x.AppType
	}
	return 0
}

func (x *CommonLog) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CommonLog) GetData_1() int32 {
	if x != nil {
		return x.Data_1
	}
	return 0
}

func (x *CommonLog) GetData_2() int32 {
	if x != nil {
		return x.Data_2
	}
	return 0
}

func (x *CommonLog) GetData_10() float64 {
	if x != nil {
		return x.Data_10
	}
	return 0
}

func (x *CommonLog) GetData_20() string {
	if x != nil {
		return x.Data_20
	}
	return ""
}

func (x *CommonLog) GetCreateTime() *TimeStamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *CommonLog) GetD_0() string {
	if x != nil {
		return x.D_0
	}
	return ""
}

func (x *CommonLog) GetD_1() string {
	if x != nil {
		return x.D_1
	}
	return ""
}

func (x *CommonLog) GetD_2() string {
	if x != nil {
		return x.D_2
	}
	return ""
}

func (x *CommonLog) GetD_3() string {
	if x != nil {
		return x.D_3
	}
	return ""
}

func (x *CommonLog) GetD_4() string {
	if x != nil {
		return x.D_4
	}
	return ""
}

func (x *CommonLog) GetD_5() string {
	if x != nil {
		return x.D_5
	}
	return ""
}

func (x *CommonLog) GetD_6() string {
	if x != nil {
		return x.D_6
	}
	return ""
}

func (x *CommonLog) GetD_7() string {
	if x != nil {
		return x.D_7
	}
	return ""
}

func (x *CommonLog) GetD_8() string {
	if x != nil {
		return x.D_8
	}
	return ""
}

func (x *CommonLog) GetD_9() string {
	if x != nil {
		return x.D_9
	}
	return ""
}

var File_pb_common_log_proto protoreflect.FileDescriptor

var file_pb_common_log_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x62, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x6c, 0x6f, 0x67, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x70, 0x62, 0x2f, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd1, 0x03, 0x0a, 0x0a, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x6c, 0x6f, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x76, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x65, 0x6e, 0x76, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x17, 0x0a, 0x07, 0x62, 0x69, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x62, 0x69, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x70, 0x70,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x61, 0x70, 0x70,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x31,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x64, 0x61, 0x74, 0x61, 0x31, 0x12, 0x15, 0x0a,
	0x06, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x32, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x64,
	0x61, 0x74, 0x61, 0x32, 0x12, 0x17, 0x0a, 0x07, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x31, 0x30, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x64, 0x61, 0x74, 0x61, 0x31, 0x30, 0x12, 0x17, 0x0a,
	0x07, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x32, 0x30, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x64, 0x61, 0x74, 0x61, 0x32, 0x30, 0x12, 0x2b, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x0f, 0x0a, 0x03, 0x64, 0x5f, 0x30, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x64, 0x30, 0x12, 0x0f, 0x0a, 0x03, 0x64, 0x5f, 0x31, 0x18, 0x0d, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x64, 0x31, 0x12, 0x0f, 0x0a, 0x03, 0x64, 0x5f, 0x32, 0x18, 0x0e, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x64, 0x32, 0x12, 0x0f, 0x0a, 0x03, 0x64, 0x5f, 0x33, 0x18, 0x0f, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x64, 0x33, 0x12, 0x0f, 0x0a, 0x03, 0x64, 0x5f, 0x34, 0x18, 0x10,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x64, 0x34, 0x12, 0x0f, 0x0a, 0x03, 0x64, 0x5f, 0x35, 0x18,
	0x11, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x64, 0x35, 0x12, 0x0f, 0x0a, 0x03, 0x64, 0x5f, 0x36,
	0x18, 0x12, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x64, 0x36, 0x12, 0x0f, 0x0a, 0x03, 0x64, 0x5f,
	0x37, 0x18, 0x13, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x64, 0x37, 0x12, 0x0f, 0x0a, 0x03, 0x64,
	0x5f, 0x38, 0x18, 0x14, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x64, 0x38, 0x12, 0x0f, 0x0a, 0x03,
	0x64, 0x5f, 0x39, 0x18, 0x15, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x64, 0x39, 0x42, 0x08, 0x5a,
	0x06, 0x2e, 0x3b, 0x70, 0x62, 0x67, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_common_log_proto_rawDescOnce sync.Once
	file_pb_common_log_proto_rawDescData = file_pb_common_log_proto_rawDesc
)

func file_pb_common_log_proto_rawDescGZIP() []byte {
	file_pb_common_log_proto_rawDescOnce.Do(func() {
		file_pb_common_log_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_common_log_proto_rawDescData)
	})
	return file_pb_common_log_proto_rawDescData
}

var file_pb_common_log_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pb_common_log_proto_goTypes = []interface{}{
	(*CommonLog)(nil), // 0: common_log
	(*TimeStamp)(nil), // 1: TimeStamp
}
var file_pb_common_log_proto_depIdxs = []int32{
	1, // 0: common_log.create_time:type_name -> TimeStamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pb_common_log_proto_init() }
func file_pb_common_log_proto_init() {
	if File_pb_common_log_proto != nil {
		return
	}
	file_pb_TimeStamp_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_pb_common_log_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommonLog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_common_log_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_common_log_proto_goTypes,
		DependencyIndexes: file_pb_common_log_proto_depIdxs,
		MessageInfos:      file_pb_common_log_proto_msgTypes,
	}.Build()
	File_pb_common_log_proto = out.File
	file_pb_common_log_proto_rawDesc = nil
	file_pb_common_log_proto_goTypes = nil
	file_pb_common_log_proto_depIdxs = nil
}
