// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.4
// source: pb/Desk.proto

package pbgo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 編譯：執行 compile_protobuf.bat
// --unique:UKey(user_id/item_id2),algo=BTREE --index:Key(index/item_id2),algo=default
type Desk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// {"comment": "索引值", "size": 23, "default": "AI", "primary_key": "default"}
	Index int32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	// {"comment": "玩家名稱", "size": 20}
	UserName string `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	// {"ignore": "true", "comment": "物品 ID", "type": "INT", "size": 5, "can_null": "true"}
	ItemId int32 `protobuf:"varint,3,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	// {"comment": "Log 建立時間", "type": "TIMESTAMP", "default": "current_timestamp()", "can_null": "false"}
	Time *TimeStamp `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *Desk) Reset() {
	*x = Desk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_Desk_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Desk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Desk) ProtoMessage() {}

func (x *Desk) ProtoReflect() protoreflect.Message {
	mi := &file_pb_Desk_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Desk.ProtoReflect.Descriptor instead.
func (*Desk) Descriptor() ([]byte, []int) {
	return file_pb_Desk_proto_rawDescGZIP(), []int{0}
}

func (x *Desk) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Desk) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *Desk) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *Desk) GetTime() *TimeStamp {
	if x != nil {
		return x.Time
	}
	return nil
}

var File_pb_Desk_proto protoreflect.FileDescriptor

var file_pb_Desk_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x70, 0x62, 0x2f, 0x44, 0x65, 0x73, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x12, 0x70, 0x62, 0x2f, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x72, 0x0a, 0x04, 0x44, 0x65, 0x73, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x69,
	0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65,
	0x78, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x17,
	0x0a, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x3b, 0x70, 0x62, 0x67,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_Desk_proto_rawDescOnce sync.Once
	file_pb_Desk_proto_rawDescData = file_pb_Desk_proto_rawDesc
)

func file_pb_Desk_proto_rawDescGZIP() []byte {
	file_pb_Desk_proto_rawDescOnce.Do(func() {
		file_pb_Desk_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_Desk_proto_rawDescData)
	})
	return file_pb_Desk_proto_rawDescData
}

var file_pb_Desk_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pb_Desk_proto_goTypes = []interface{}{
	(*Desk)(nil),      // 0: Desk
	(*TimeStamp)(nil), // 1: TimeStamp
}
var file_pb_Desk_proto_depIdxs = []int32{
	1, // 0: Desk.time:type_name -> TimeStamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pb_Desk_proto_init() }
func file_pb_Desk_proto_init() {
	if File_pb_Desk_proto != nil {
		return
	}
	file_pb_TimeStamp_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_pb_Desk_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Desk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_Desk_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_Desk_proto_goTypes,
		DependencyIndexes: file_pb_Desk_proto_depIdxs,
		MessageInfos:      file_pb_Desk_proto_msgTypes,
	}.Build()
	File_pb_Desk_proto = out.File
	file_pb_Desk_proto_rawDesc = nil
	file_pb_Desk_proto_goTypes = nil
	file_pb_Desk_proto_depIdxs = nil
}
