// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.4
// source: pb/history_log.proto

package pbgo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HistoryLog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// {"comment": "流水號", "type": "BIGINT", "size": 20, "default": "ai", "primary_key": "default"}
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// {"comment": "玩家 ID", "type": "BIGINT", "size": 20, "default": "nil", "can_null": "false"}
	Uid int64 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	// {"comment": "分類\r\n1=總等級\r\n2=金錢\r\n3=寶石\r\n4=裝備\r\n5=角色\r\n6=天賦\r\n7=寵物"}
	// {"type": "SMALLINT", "size": 6, "default": "0", "can_null": "true"}
	Type int32 `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	// {"comment": "子分類\r\n0=無特別原因\r\n1=+LV\r\n2=拆LV\r\n3=+鬥魂\r\n4=拆鬥魂\r\n5=完全分解"}
	// {"type": "SMALLINT", "size": 6, "default": "0", "can_null": "true"}
	Type1 int32 `protobuf:"varint,4,opt,name=type1,proto3" json:"type1,omitempty"`
	// {"comment": "原因\r\n0=無特別原因\r\n1=消費金錢\r\n2=消費寶石\r\n3=消費道具\r\n4=消費金錢+道具"}
	// {"type": "SMALLINT", "size": 6, "default": "0", "can_null": "true"}
	Cause int32 `protobuf:"varint,5,opt,name=cause,proto3" json:"cause,omitempty"`
	// {"comment": "自定義資料 0", "type": "INT", "size": 11, "default": "0", "can_null": "false"}
	D0 int32 `protobuf:"varint,6,opt,name=d0,proto3" json:"d0,omitempty"`
	// {"comment": "自定義資料 1", "type": "INT", "size": 11, "default": "0", "can_null": "false"}
	D1 int32 `protobuf:"varint,7,opt,name=d1,proto3" json:"d1,omitempty"`
	// {"comment": "自定義資料 2", "type": "INT", "size": 11, "default": "0", "can_null": "false"}
	D2 int32 `protobuf:"varint,8,opt,name=d2,proto3" json:"d2,omitempty"`
	// {"comment": "自定義資料 3", "type": "INT", "size": 11, "default": "0", "can_null": "false"}
	D3 int32 `protobuf:"varint,9,opt,name=d3,proto3" json:"d3,omitempty"`
	// {"comment": "帳號建立時間", "type": "TIMESTAMP", "default": "current_timestamp()", "can_null": "false"}
	CreateTime *TimeStamp `protobuf:"bytes,10,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
}

func (x *HistoryLog) Reset() {
	*x = HistoryLog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_history_log_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HistoryLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryLog) ProtoMessage() {}

func (x *HistoryLog) ProtoReflect() protoreflect.Message {
	mi := &file_pb_history_log_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryLog.ProtoReflect.Descriptor instead.
func (*HistoryLog) Descriptor() ([]byte, []int) {
	return file_pb_history_log_proto_rawDescGZIP(), []int{0}
}

func (x *HistoryLog) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *HistoryLog) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *HistoryLog) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *HistoryLog) GetType1() int32 {
	if x != nil {
		return x.Type1
	}
	return 0
}

func (x *HistoryLog) GetCause() int32 {
	if x != nil {
		return x.Cause
	}
	return 0
}

func (x *HistoryLog) GetD0() int32 {
	if x != nil {
		return x.D0
	}
	return 0
}

func (x *HistoryLog) GetD1() int32 {
	if x != nil {
		return x.D1
	}
	return 0
}

func (x *HistoryLog) GetD2() int32 {
	if x != nil {
		return x.D2
	}
	return 0
}

func (x *HistoryLog) GetD3() int32 {
	if x != nil {
		return x.D3
	}
	return 0
}

func (x *HistoryLog) GetCreateTime() *TimeStamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

var File_pb_history_log_proto protoreflect.FileDescriptor

var file_pb_history_log_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x62, 0x2f, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x5f, 0x6c, 0x6f, 0x67,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x70, 0x62, 0x2f, 0x54, 0x69, 0x6d, 0x65, 0x53,
	0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xdc, 0x01, 0x0a, 0x0b, 0x68,
	0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x5f, 0x6c, 0x6f, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x79, 0x70, 0x65, 0x31, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x74, 0x79, 0x70, 0x65, 0x31, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x61, 0x75, 0x73, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x61, 0x75, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x64, 0x30, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x64, 0x30, 0x12, 0x0e, 0x0a, 0x02,
	0x64, 0x31, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x64, 0x31, 0x12, 0x0e, 0x0a, 0x02,
	0x64, 0x32, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x64, 0x32, 0x12, 0x0e, 0x0a, 0x02,
	0x64, 0x33, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x64, 0x33, 0x12, 0x2b, 0x0a, 0x0b,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0a, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x3b, 0x70,
	0x62, 0x67, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_history_log_proto_rawDescOnce sync.Once
	file_pb_history_log_proto_rawDescData = file_pb_history_log_proto_rawDesc
)

func file_pb_history_log_proto_rawDescGZIP() []byte {
	file_pb_history_log_proto_rawDescOnce.Do(func() {
		file_pb_history_log_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_history_log_proto_rawDescData)
	})
	return file_pb_history_log_proto_rawDescData
}

var file_pb_history_log_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pb_history_log_proto_goTypes = []interface{}{
	(*HistoryLog)(nil), // 0: history_log
	(*TimeStamp)(nil),  // 1: TimeStamp
}
var file_pb_history_log_proto_depIdxs = []int32{
	1, // 0: history_log.create_time:type_name -> TimeStamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pb_history_log_proto_init() }
func file_pb_history_log_proto_init() {
	if File_pb_history_log_proto != nil {
		return
	}
	file_pb_TimeStamp_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_pb_history_log_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HistoryLog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_history_log_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_history_log_proto_goTypes,
		DependencyIndexes: file_pb_history_log_proto_depIdxs,
		MessageInfos:      file_pb_history_log_proto_msgTypes,
	}.Build()
	File_pb_history_log_proto = out.File
	file_pb_history_log_proto_rawDesc = nil
	file_pb_history_log_proto_goTypes = nil
	file_pb_history_log_proto_depIdxs = nil
}
