// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.4
// source: pb/item_log.proto

package pbgo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// {"index": [{"name": "索引 2", "columns": ["create_time", "uid"]}]}
type ItemLog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// {"comment": "流水號", "type": "BIGINT", "size": 20, "default": "ai", "primary_key": "default"}
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// {"comment": "玩家 ID", "type": "BIGINT", "size": 20, "default": "nil", "can_null": "false"}
	Uid int64 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	// {"comment": "背包ID (-1表示裝備欄)", "type": "SMALLINT", "size": 6, "default": "nil", "can_null": "false"}
	Seat1 int32 `protobuf:"varint,3,opt,name=seat1,proto3" json:"seat1,omitempty"`
	// {"comment": "道具在背包中的位置", "type": "SMALLINT", "size": 6, "default": "nil", "can_null": "false"}
	Seat2 int32 `protobuf:"varint,4,opt,name=seat2,proto3" json:"seat2,omitempty"`
	// {"comment": "道具編號 (0=無效)", "type": "INT", "size": 11, "default": "0", "can_null": "false"}
	ItemId int32 `protobuf:"varint,5,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	// {"comment": "原有虛寶數量", "type": "SMALLINT", "size": 6, "default": "0", "can_null": "false"}
	OldNum int32 `protobuf:"varint,6,opt,name=old_num,json=oldNum,proto3" json:"old_num,omitempty"`
	// {"comment": "增加的虛寶數量", "type": "SMALLINT", "size": 6, "default": "0", "can_null": "false"}
	AddNum int32 `protobuf:"varint,7,opt,name=add_num,json=addNum,proto3" json:"add_num,omitempty"`
	// {"comment": "最後虛寶數量", "type": "SMALLINT", "size": 6, "default": "0", "can_null": "false"}
	NewNum int32 `protobuf:"varint,8,opt,name=new_num,json=newNum,proto3" json:"new_num,omitempty"`
	// {"comment": "道具 LV", "type": "SMALLINT", "size": 5, "default": "0", "can_null": "false", "unsigned": "true"}
	Lv int32 `protobuf:"varint,9,opt,name=lv,proto3" json:"lv,omitempty"`
	// {"comment": "道具 EXP", "type": "SMALLINT", "size": 6, "default": "0", "can_null": "false", "unsigned": "true"}
	Exp int32 `protobuf:"varint,10,opt,name=exp,proto3" json:"exp,omitempty"`
	// {"comment": "鬥魂 LV", "type": "SMALLINT", "size": 5, "default": "0", "can_null": "false", "unsigned": "true"}
	EvoLv int32 `protobuf:"varint,11,opt,name=evo_lv,json=evoLv,proto3" json:"evo_lv,omitempty"`
	// {"comment": "鬥魂 EXP", "type": "SMALLINT", "size": 6, "default": "0", "can_null": "false", "unsigned": "true"}
	EvoExp int32 `protobuf:"varint,12,opt,name=evo_exp,json=evoExp,proto3" json:"evo_exp,omitempty"`
	// {"comment": "原因(0=使用，1=合成，2=因錯誤而回收)"}
	// {"type": "SMALLINT", "size": 6, "default": "nil", "can_null": "true"}
	Cause int32 `protobuf:"varint,13,opt,name=cause,proto3" json:"cause,omitempty"`
	// {"comment": "資料建立時間", "type": "TIMESTAMP", "size": 6, "default": "current_timestamp()", "can_null": "false"}
	CreateTime *TimeStamp `protobuf:"bytes,14,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
}

func (x *ItemLog) Reset() {
	*x = ItemLog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_item_log_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemLog) ProtoMessage() {}

func (x *ItemLog) ProtoReflect() protoreflect.Message {
	mi := &file_pb_item_log_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemLog.ProtoReflect.Descriptor instead.
func (*ItemLog) Descriptor() ([]byte, []int) {
	return file_pb_item_log_proto_rawDescGZIP(), []int{0}
}

func (x *ItemLog) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ItemLog) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ItemLog) GetSeat1() int32 {
	if x != nil {
		return x.Seat1
	}
	return 0
}

func (x *ItemLog) GetSeat2() int32 {
	if x != nil {
		return x.Seat2
	}
	return 0
}

func (x *ItemLog) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *ItemLog) GetOldNum() int32 {
	if x != nil {
		return x.OldNum
	}
	return 0
}

func (x *ItemLog) GetAddNum() int32 {
	if x != nil {
		return x.AddNum
	}
	return 0
}

func (x *ItemLog) GetNewNum() int32 {
	if x != nil {
		return x.NewNum
	}
	return 0
}

func (x *ItemLog) GetLv() int32 {
	if x != nil {
		return x.Lv
	}
	return 0
}

func (x *ItemLog) GetExp() int32 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *ItemLog) GetEvoLv() int32 {
	if x != nil {
		return x.EvoLv
	}
	return 0
}

func (x *ItemLog) GetEvoExp() int32 {
	if x != nil {
		return x.EvoExp
	}
	return 0
}

func (x *ItemLog) GetCause() int32 {
	if x != nil {
		return x.Cause
	}
	return 0
}

func (x *ItemLog) GetCreateTime() *TimeStamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

var File_pb_item_log_proto protoreflect.FileDescriptor

var file_pb_item_log_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x62, 0x2f, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x6c, 0x6f, 0x67, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x70, 0x62, 0x2f, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd1, 0x02, 0x0a, 0x08, 0x69, 0x74, 0x65, 0x6d,
	0x5f, 0x6c, 0x6f, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x65, 0x61, 0x74, 0x31, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x65, 0x61, 0x74, 0x31, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x65, 0x61, 0x74, 0x32, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x65, 0x61,
	0x74, 0x32, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x6f,
	0x6c, 0x64, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x6c,
	0x64, 0x4e, 0x75, 0x6d, 0x12, 0x17, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x5f, 0x6e, 0x75, 0x6d, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x61, 0x64, 0x64, 0x4e, 0x75, 0x6d, 0x12, 0x17, 0x0a,
	0x07, 0x6e, 0x65, 0x77, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x6e, 0x65, 0x77, 0x4e, 0x75, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x6c, 0x76, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x02, 0x6c, 0x76, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x78, 0x70, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x65, 0x78, 0x70, 0x12, 0x15, 0x0a, 0x06, 0x65, 0x76, 0x6f, 0x5f,
	0x6c, 0x76, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x65, 0x76, 0x6f, 0x4c, 0x76, 0x12,
	0x17, 0x0a, 0x07, 0x65, 0x76, 0x6f, 0x5f, 0x65, 0x78, 0x70, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x65, 0x76, 0x6f, 0x45, 0x78, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x61, 0x75, 0x73,
	0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x61, 0x75, 0x73, 0x65, 0x12, 0x2b,
	0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x0e, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x42, 0x08, 0x5a, 0x06, 0x2e,
	0x3b, 0x70, 0x62, 0x67, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_item_log_proto_rawDescOnce sync.Once
	file_pb_item_log_proto_rawDescData = file_pb_item_log_proto_rawDesc
)

func file_pb_item_log_proto_rawDescGZIP() []byte {
	file_pb_item_log_proto_rawDescOnce.Do(func() {
		file_pb_item_log_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_item_log_proto_rawDescData)
	})
	return file_pb_item_log_proto_rawDescData
}

var file_pb_item_log_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pb_item_log_proto_goTypes = []interface{}{
	(*ItemLog)(nil),   // 0: item_log
	(*TimeStamp)(nil), // 1: TimeStamp
}
var file_pb_item_log_proto_depIdxs = []int32{
	1, // 0: item_log.create_time:type_name -> TimeStamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pb_item_log_proto_init() }
func file_pb_item_log_proto_init() {
	if File_pb_item_log_proto != nil {
		return
	}
	file_pb_TimeStamp_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_pb_item_log_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemLog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_item_log_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_item_log_proto_goTypes,
		DependencyIndexes: file_pb_item_log_proto_depIdxs,
		MessageInfos:      file_pb_item_log_proto_msgTypes,
	}.Build()
	File_pb_item_log_proto = out.File
	file_pb_item_log_proto_rawDesc = nil
	file_pb_item_log_proto_goTypes = nil
	file_pb_item_log_proto_depIdxs = nil
}
