// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.4
// source: pb/login_award_7.proto

package pbgo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 編譯：執行 compile_protobuf.bat
type LoginAward_7 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// {"comment": "第幾天", "type": "INT", "size": 11, "default": "nil", "can_null": "false"}
	Day int32 `protobuf:"varint,1,opt,name=day,proto3" json:"day,omitempty"`
	// {"comment": "行動值", "type": "INT", "size": 1, "default": "0", "can_null": "false"}
	Act int32 `protobuf:"varint,2,opt,name=act,proto3" json:"act,omitempty"`
	// {"comment": "錢", "type": "INT", "size": 11, "default": "0", "can_null": "false"}
	Gold int32 `protobuf:"varint,3,opt,name=gold,proto3" json:"gold,omitempty"`
	// {"comment": "寶石", "type": "SMALLINT", "size": 6, "default": "0", "can_null": "false"}
	Gem int32 `protobuf:"varint,4,opt,name=gem,proto3" json:"gem,omitempty"`
	// {"comment": "一般鑰匙", "type": "TINYINT", "size": 4, "default": "0", "can_null": "false"}
	Key_0 int32 `protobuf:"varint,5,opt,name=key_0,json=key0,proto3" json:"key_0,omitempty"`
	// {"comment": "黑曜石鑰匙", "type": "TINYINT", "size": 4, "default": "0", "can_null": "false"}
	Key_1 int32 `protobuf:"varint,6,opt,name=key_1,json=key1,proto3" json:"key_1,omitempty"`
	// {"comment": "通關獎勵", "type": "VARCHAR", "default": "''", "can_null": "false"}
	Award string `protobuf:"bytes,7,opt,name=award,proto3" json:"award,omitempty"`
}

func (x *LoginAward_7) Reset() {
	*x = LoginAward_7{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_login_award_7_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginAward_7) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginAward_7) ProtoMessage() {}

func (x *LoginAward_7) ProtoReflect() protoreflect.Message {
	mi := &file_pb_login_award_7_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginAward_7.ProtoReflect.Descriptor instead.
func (*LoginAward_7) Descriptor() ([]byte, []int) {
	return file_pb_login_award_7_proto_rawDescGZIP(), []int{0}
}

func (x *LoginAward_7) GetDay() int32 {
	if x != nil {
		return x.Day
	}
	return 0
}

func (x *LoginAward_7) GetAct() int32 {
	if x != nil {
		return x.Act
	}
	return 0
}

func (x *LoginAward_7) GetGold() int32 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *LoginAward_7) GetGem() int32 {
	if x != nil {
		return x.Gem
	}
	return 0
}

func (x *LoginAward_7) GetKey_0() int32 {
	if x != nil {
		return x.Key_0
	}
	return 0
}

func (x *LoginAward_7) GetKey_1() int32 {
	if x != nil {
		return x.Key_1
	}
	return 0
}

func (x *LoginAward_7) GetAward() string {
	if x != nil {
		return x.Award
	}
	return ""
}

var File_pb_login_award_7_proto protoreflect.FileDescriptor

var file_pb_login_award_7_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x62, 0x2f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x61, 0x77, 0x61, 0x72, 0x64,
	0x5f, 0x37, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x99, 0x01, 0x0a, 0x0d, 0x6c, 0x6f, 0x67,
	0x69, 0x6e, 0x5f, 0x61, 0x77, 0x61, 0x72, 0x64, 0x5f, 0x37, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x61,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x64, 0x61, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x61, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x61, 0x63, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x67, 0x6f, 0x6c, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x67, 0x6f,
	0x6c, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x67, 0x65, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x67, 0x65, 0x6d, 0x12, 0x13, 0x0a, 0x05, 0x6b, 0x65, 0x79, 0x5f, 0x30, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x30, 0x12, 0x13, 0x0a, 0x05, 0x6b, 0x65, 0x79,
	0x5f, 0x31, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x31, 0x12, 0x14,
	0x0a, 0x05, 0x61, 0x77, 0x61, 0x72, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61,
	0x77, 0x61, 0x72, 0x64, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x3b, 0x70, 0x62, 0x67, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_login_award_7_proto_rawDescOnce sync.Once
	file_pb_login_award_7_proto_rawDescData = file_pb_login_award_7_proto_rawDesc
)

func file_pb_login_award_7_proto_rawDescGZIP() []byte {
	file_pb_login_award_7_proto_rawDescOnce.Do(func() {
		file_pb_login_award_7_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_login_award_7_proto_rawDescData)
	})
	return file_pb_login_award_7_proto_rawDescData
}

var file_pb_login_award_7_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pb_login_award_7_proto_goTypes = []interface{}{
	(*LoginAward_7)(nil), // 0: login_award_7
}
var file_pb_login_award_7_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_login_award_7_proto_init() }
func file_pb_login_award_7_proto_init() {
	if File_pb_login_award_7_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_login_award_7_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginAward_7); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_login_award_7_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_login_award_7_proto_goTypes,
		DependencyIndexes: file_pb_login_award_7_proto_depIdxs,
		MessageInfos:      file_pb_login_award_7_proto_msgTypes,
	}.Build()
	File_pb_login_award_7_proto = out.File
	file_pb_login_award_7_proto_rawDesc = nil
	file_pb_login_award_7_proto_goTypes = nil
	file_pb_login_award_7_proto_depIdxs = nil
}
