// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.4
// source: pb/online_ppl.proto

package pbgo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// {"index": [{"name": "索引 2", "columns": ["env_type", "create_time", "game_code", "server_code"]}]}
type OnlinePpl struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// {"comment": "流水號", "type": "INT", "size": 11, "default": "ai", "primary_key": "default"}
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// {"comment": "環境類別 0=作者開發環境，1=開發測試環境，2=運營測試環境，3=審核環境，4=正式環境"}
	// {"type": "TINYINT", "size": 4, "default": "0", "can_null": "false"}
	EnvType int32 `protobuf:"varint,2,opt,name=env_type,json=envType,proto3" json:"env_type,omitempty"`
	// {"comment": "遊戲編號(-1表示全部)", "type": "SMALLINT", "size": 6, "default": "0", "can_null": "false"}
	GameCode int32 `protobuf:"varint,3,opt,name=game_code,json=gameCode,proto3" json:"game_code,omitempty"`
	// {"comment": "伺服器編號(-1表示全部)", "type": "SMALLINT", "size": 6, "default": "0", "can_null": "false"}
	ServerCode int32 `protobuf:"varint,4,opt,name=server_code,json=serverCode,proto3" json:"server_code,omitempty"`
	// {"comment": "人數", "type": "INT", "size": 11, "default": "0", "can_null": "false"}
	PplNum int32 `protobuf:"varint,5,opt,name=ppl_num,json=pplNum,proto3" json:"ppl_num,omitempty"`
	// {"comment": "機器人數量", "type": "INT", "size": 11, "default": "0", "can_null": "false"}
	RobotNum int32 `protobuf:"varint,6,opt,name=robot_num,json=robotNum,proto3" json:"robot_num,omitempty"`
	// {"comment": "資料建立時間", "type": "TIMESTAMP", "default": "current_timestamp()", "can_null": "false"}
	CreateTime *TimeStamp `protobuf:"bytes,7,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
}

func (x *OnlinePpl) Reset() {
	*x = OnlinePpl{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_online_ppl_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlinePpl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlinePpl) ProtoMessage() {}

func (x *OnlinePpl) ProtoReflect() protoreflect.Message {
	mi := &file_pb_online_ppl_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlinePpl.ProtoReflect.Descriptor instead.
func (*OnlinePpl) Descriptor() ([]byte, []int) {
	return file_pb_online_ppl_proto_rawDescGZIP(), []int{0}
}

func (x *OnlinePpl) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OnlinePpl) GetEnvType() int32 {
	if x != nil {
		return x.EnvType
	}
	return 0
}

func (x *OnlinePpl) GetGameCode() int32 {
	if x != nil {
		return x.GameCode
	}
	return 0
}

func (x *OnlinePpl) GetServerCode() int32 {
	if x != nil {
		return x.ServerCode
	}
	return 0
}

func (x *OnlinePpl) GetPplNum() int32 {
	if x != nil {
		return x.PplNum
	}
	return 0
}

func (x *OnlinePpl) GetRobotNum() int32 {
	if x != nil {
		return x.RobotNum
	}
	return 0
}

func (x *OnlinePpl) GetCreateTime() *TimeStamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

var File_pb_online_ppl_proto protoreflect.FileDescriptor

var file_pb_online_ppl_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x62, 0x2f, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x70, 0x70, 0x6c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x70, 0x62, 0x2f, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd8, 0x01, 0x0a, 0x0a, 0x6f, 0x6e,
	0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x70, 0x70, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x76, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x65, 0x6e, 0x76, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x70, 0x6c, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x70, 0x70, 0x6c, 0x4e, 0x75, 0x6d, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x6f,
	0x62, 0x6f, 0x74, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x72,
	0x6f, 0x62, 0x6f, 0x74, 0x4e, 0x75, 0x6d, 0x12, 0x2b, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x3b, 0x70, 0x62, 0x67, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_online_ppl_proto_rawDescOnce sync.Once
	file_pb_online_ppl_proto_rawDescData = file_pb_online_ppl_proto_rawDesc
)

func file_pb_online_ppl_proto_rawDescGZIP() []byte {
	file_pb_online_ppl_proto_rawDescOnce.Do(func() {
		file_pb_online_ppl_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_online_ppl_proto_rawDescData)
	})
	return file_pb_online_ppl_proto_rawDescData
}

var file_pb_online_ppl_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pb_online_ppl_proto_goTypes = []interface{}{
	(*OnlinePpl)(nil), // 0: online_ppl
	(*TimeStamp)(nil), // 1: TimeStamp
}
var file_pb_online_ppl_proto_depIdxs = []int32{
	1, // 0: online_ppl.create_time:type_name -> TimeStamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pb_online_ppl_proto_init() }
func file_pb_online_ppl_proto_init() {
	if File_pb_online_ppl_proto != nil {
		return
	}
	file_pb_TimeStamp_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_pb_online_ppl_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlinePpl); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_online_ppl_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_online_ppl_proto_goTypes,
		DependencyIndexes: file_pb_online_ppl_proto_depIdxs,
		MessageInfos:      file_pb_online_ppl_proto_msgTypes,
	}.Build()
	File_pb_online_ppl_proto = out.File
	file_pb_online_ppl_proto_rawDesc = nil
	file_pb_online_ppl_proto_goTypes = nil
	file_pb_online_ppl_proto_depIdxs = nil
}
