// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.4
// source: pb/pay_log.proto

package pbgo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// {"index": [{"name": "索引 2", "columns": ["create_time", "pay_platform"]}]}
// {"index": [{"name": "索引 3", "columns": ["create_time", "game_code"]}]}
type PayLog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// {"comment": "流水號", "type": "BIGINT", "size": 20, "default": "ai", "primary_key": "default"}
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// {"comment": "遊戲編號", "type": "SMALLINT", "size": 6, "default": "0", "can_null": "false"}
	GameCode int32 `protobuf:"varint,2,opt,name=game_code,json=gameCode,proto3" json:"game_code,omitempty"`
	// {"comment": "Server 編號", "type": "SMALLINT", "size": 6, "default": "0", "can_null": "false"}
	ServerCode int32 `protobuf:"varint,3,opt,name=server_code,json=serverCode,proto3" json:"server_code,omitempty"`
	// {"comment": "玩家 ID", "type": "BIGINT", "size": 20, "default": "0", "can_null": "false"}
	Uid int64 `protobuf:"varint,4,opt,name=uid,proto3" json:"uid,omitempty"`
	// {"comment": "付費平台\r\n1=Google\r\n2=Apple\r\n3=FB\r\n"}
	// {"type": "TINYINT", "size": 4, "default": "0", "can_null": "false"}
	PayPlatform int32 `protobuf:"varint,5,opt,name=pay_platform,json=payPlatform,proto3" json:"pay_platform,omitempty"`
	// {"comment": "交易 ID", "type": "VARCHAR", "size": 32, "default": "''", "can_null": "false"}
	TradeId string `protobuf:"bytes,6,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`
	// {"comment": "購買項目的 ID", "type": "VARCHAR", "size": 64, "default": "''", "can_null": "false"}
	BuyOptionsId string `protobuf:"bytes,7,opt,name=buy_options_id,json=buyOptionsId,proto3" json:"buy_options_id,omitempty"`
	// {"comment": "交易金額單位\r\n0=台幣\r\n1=人民幣\r\n2=美金\r\n"}
	// {"type": "TINYINT", "size": 4, "default": "0", "can_null": "false"}
	CashType int32 `protobuf:"varint,8,opt,name=cash_type,json=cashType,proto3" json:"cash_type,omitempty"`
	// {"comment": "交易金額", "type": "DOUBLE", "default": "0", "can_null": "false"}
	Cash float64 `protobuf:"fixed64,9,opt,name=cash,proto3" json:"cash,omitempty"`
	// {"comment": "金幣別", "type": "TINYINT", "size": 4, "default": "0", "can_null": "false"}
	GoldType int32 `protobuf:"varint,10,opt,name=gold_type,json=goldType,proto3" json:"gold_type,omitempty"`
	// {"comment": "增加多少金幣", "type": "BIGINT", "size": 20, "default": "0", "can_null": "false"}
	AddGold int32 `protobuf:"varint,11,opt,name=add_gold,json=addGold,proto3" json:"add_gold,omitempty"`
	// {"comment": "貢獻值", "type": "BIGINT", "size": 20, "default": "0", "can_null": "false"}
	Contribute int64 `protobuf:"varint,12,opt,name=contribute,proto3" json:"contribute,omitempty"`
	// {"comment": "錯誤碼", "type": "INT", "size": 11, "default": "0", "can_null": "false"}
	ErrorCode int64 `protobuf:"varint,13,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	// {"comment": "資料建立時間", "type": "TIMESTAMP", "default": "current_timestamp()", "can_null": "false"}
	CreateTime *TimeStamp `protobuf:"bytes,14,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
}

func (x *PayLog) Reset() {
	*x = PayLog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pay_log_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PayLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayLog) ProtoMessage() {}

func (x *PayLog) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pay_log_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayLog.ProtoReflect.Descriptor instead.
func (*PayLog) Descriptor() ([]byte, []int) {
	return file_pb_pay_log_proto_rawDescGZIP(), []int{0}
}

func (x *PayLog) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PayLog) GetGameCode() int32 {
	if x != nil {
		return x.GameCode
	}
	return 0
}

func (x *PayLog) GetServerCode() int32 {
	if x != nil {
		return x.ServerCode
	}
	return 0
}

func (x *PayLog) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *PayLog) GetPayPlatform() int32 {
	if x != nil {
		return x.PayPlatform
	}
	return 0
}

func (x *PayLog) GetTradeId() string {
	if x != nil {
		return x.TradeId
	}
	return ""
}

func (x *PayLog) GetBuyOptionsId() string {
	if x != nil {
		return x.BuyOptionsId
	}
	return ""
}

func (x *PayLog) GetCashType() int32 {
	if x != nil {
		return x.CashType
	}
	return 0
}

func (x *PayLog) GetCash() float64 {
	if x != nil {
		return x.Cash
	}
	return 0
}

func (x *PayLog) GetGoldType() int32 {
	if x != nil {
		return x.GoldType
	}
	return 0
}

func (x *PayLog) GetAddGold() int32 {
	if x != nil {
		return x.AddGold
	}
	return 0
}

func (x *PayLog) GetContribute() int64 {
	if x != nil {
		return x.Contribute
	}
	return 0
}

func (x *PayLog) GetErrorCode() int64 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *PayLog) GetCreateTime() *TimeStamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

var File_pb_pay_log_proto protoreflect.FileDescriptor

var file_pb_pay_log_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x62, 0x2f, 0x70, 0x61, 0x79, 0x5f, 0x6c, 0x6f, 0x67, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x12, 0x70, 0x62, 0x2f, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa2, 0x03, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x5f, 0x6c,
	0x6f, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75,
	0x69, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x61, 0x79, 0x5f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f,
	0x72, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x70, 0x61, 0x79, 0x50, 0x6c, 0x61,
	0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x72, 0x61, 0x64, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x72, 0x61, 0x64, 0x65, 0x49, 0x64,
	0x12, 0x24, 0x0a, 0x0e, 0x62, 0x75, 0x79, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x5f,
	0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x62, 0x75, 0x79, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x61, 0x73, 0x68, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x63, 0x61, 0x73, 0x68, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x61, 0x73, 0x68, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x04, 0x63, 0x61, 0x73, 0x68, 0x12, 0x1b, 0x0a, 0x09, 0x67, 0x6f, 0x6c, 0x64, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x67, 0x6f, 0x6c, 0x64,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x64, 0x64, 0x5f, 0x67, 0x6f, 0x6c, 0x64,
	0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x61, 0x64, 0x64, 0x47, 0x6f, 0x6c, 0x64, 0x12,
	0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x18, 0x0c, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x12,
	0x1d, 0x0a, 0x0a, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x0d, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x2b,
	0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x0e, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x42, 0x08, 0x5a, 0x06, 0x2e,
	0x3b, 0x70, 0x62, 0x67, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_pay_log_proto_rawDescOnce sync.Once
	file_pb_pay_log_proto_rawDescData = file_pb_pay_log_proto_rawDesc
)

func file_pb_pay_log_proto_rawDescGZIP() []byte {
	file_pb_pay_log_proto_rawDescOnce.Do(func() {
		file_pb_pay_log_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_pay_log_proto_rawDescData)
	})
	return file_pb_pay_log_proto_rawDescData
}

var file_pb_pay_log_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pb_pay_log_proto_goTypes = []interface{}{
	(*PayLog)(nil),    // 0: pay_log
	(*TimeStamp)(nil), // 1: TimeStamp
}
var file_pb_pay_log_proto_depIdxs = []int32{
	1, // 0: pay_log.create_time:type_name -> TimeStamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pb_pay_log_proto_init() }
func file_pb_pay_log_proto_init() {
	if File_pb_pay_log_proto != nil {
		return
	}
	file_pb_TimeStamp_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_pb_pay_log_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PayLog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_pay_log_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_pay_log_proto_goTypes,
		DependencyIndexes: file_pb_pay_log_proto_depIdxs,
		MessageInfos:      file_pb_pay_log_proto_msgTypes,
	}.Build()
	File_pb_pay_log_proto = out.File
	file_pb_pay_log_proto_rawDesc = nil
	file_pb_pay_log_proto_goTypes = nil
	file_pb_pay_log_proto_depIdxs = nil
}
