// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.4
// source: pb/user_item.proto

package pbgo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// {"comment": "玩家的 uid", "type": "BIGINT", "size": 20, "default": "nil", "can_null": "false"}
	Uid int64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// {"comment": "背包ID(-1表示裝備欄)", "type": "SMALLINT", "size": 6, "default": "nil", "can_null": "false"}
	Seat1 int64 `protobuf:"varint,2,opt,name=seat1,proto3" json:"seat1,omitempty"`
	// {"comment": "道具在背包中的位置", "type": "SMALLINT", "size": 6, "default": "nil", "can_null": "false"}
	Seat2 int32 `protobuf:"varint,3,opt,name=seat2,proto3" json:"seat2,omitempty"`
	// {"comment": "道具編號(0=無效)", "type": "INT", "size": 11, "default": "0", "can_null": "false"}
	ItemId int32 `protobuf:"varint,4,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	// {"comment": "道具數量", "type": "INT", "size": 11, "default": "0", "can_null": "false"}
	Num int32 `protobuf:"varint,5,opt,name=num,proto3" json:"num,omitempty"`
	// {"comment": "道具 LV", "type": "SMALLINT", "size": 5, "default": "0", "can_null": "false", "unsigned": "true"}
	Lv int32 `protobuf:"varint,6,opt,name=lv,proto3" json:"lv,omitempty"`
	// {"comment": "道具 EXP", "type": "INT", "size": 10, "default": "0", "can_null": "false", "unsigned": "true"}
	Exp int32 `protobuf:"varint,7,opt,name=exp,proto3" json:"exp,omitempty"`
	// {"comment": "鬥魂 LV", "type": "SMALLINT", "size": 5, "default": "0", "can_null": "false", "unsigned": "true"}
	EvoLv int32 `protobuf:"varint,8,opt,name=evo_lv,json=evoLv,proto3" json:"evo_lv,omitempty"`
	// {"comment": "鬥魂 EXP", "type": "INT", "size": 10, "default": "0", "can_null": "false", "unsigned": "true"}
	EvoExp int32 `protobuf:"varint,9,opt,name=evo_exp,json=evoExp,proto3" json:"evo_exp,omitempty"`
	// {"comment": "特別位元旗號", "type": "SMALLINT", "size": 5, "default": "0", "can_null": "false", "unsigned": "true"}
	SpFl int32 `protobuf:"varint,10,opt,name=sp_fl,json=spFl,proto3" json:"sp_fl,omitempty"`
	// {"comment": "唯一碼", "type": "BIGINT", "size": 20, "default": "nil", "can_null": "false"}
	UniqueCode int64 `protobuf:"varint,11,opt,name=unique_code,json=uniqueCode,proto3" json:"unique_code,omitempty"`
	// {"comment": "資料建立時間", "type": "TIMESTAMP", "default": "current_timestamp()", "can_null": "false"}
	CreateTime *TimeStamp `protobuf:"bytes,12,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// {"comment": "最後一次的更新時間", "type": "TIMESTAMP", "can_null": "false"}
	// {"default": "current_timestamp()", "update": "current_timestamp()"}
	LastUpdateTime *TimeStamp `protobuf:"bytes,13,opt,name=last_update_time,json=lastUpdateTime,proto3" json:"last_update_time,omitempty"`
}

func (x *UserItem) Reset() {
	*x = UserItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_user_item_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserItem) ProtoMessage() {}

func (x *UserItem) ProtoReflect() protoreflect.Message {
	mi := &file_pb_user_item_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserItem.ProtoReflect.Descriptor instead.
func (*UserItem) Descriptor() ([]byte, []int) {
	return file_pb_user_item_proto_rawDescGZIP(), []int{0}
}

func (x *UserItem) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *UserItem) GetSeat1() int64 {
	if x != nil {
		return x.Seat1
	}
	return 0
}

func (x *UserItem) GetSeat2() int32 {
	if x != nil {
		return x.Seat2
	}
	return 0
}

func (x *UserItem) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *UserItem) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *UserItem) GetLv() int32 {
	if x != nil {
		return x.Lv
	}
	return 0
}

func (x *UserItem) GetExp() int32 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *UserItem) GetEvoLv() int32 {
	if x != nil {
		return x.EvoLv
	}
	return 0
}

func (x *UserItem) GetEvoExp() int32 {
	if x != nil {
		return x.EvoExp
	}
	return 0
}

func (x *UserItem) GetSpFl() int32 {
	if x != nil {
		return x.SpFl
	}
	return 0
}

func (x *UserItem) GetUniqueCode() int64 {
	if x != nil {
		return x.UniqueCode
	}
	return 0
}

func (x *UserItem) GetCreateTime() *TimeStamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *UserItem) GetLastUpdateTime() *TimeStamp {
	if x != nil {
		return x.LastUpdateTime
	}
	return nil
}

var File_pb_user_item_proto protoreflect.FileDescriptor

var file_pb_user_item_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x62, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x70, 0x62, 0x2f, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61,
	0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xdf, 0x02, 0x0a, 0x09, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x65, 0x61, 0x74,
	0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x65, 0x61, 0x74, 0x31, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x65, 0x61, 0x74, 0x32, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73,
	0x65, 0x61, 0x74, 0x32, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x10, 0x0a,
	0x03, 0x6e, 0x75, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x12,
	0x0e, 0x0a, 0x02, 0x6c, 0x76, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x6c, 0x76, 0x12,
	0x10, 0x0a, 0x03, 0x65, 0x78, 0x70, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x65, 0x78,
	0x70, 0x12, 0x15, 0x0a, 0x06, 0x65, 0x76, 0x6f, 0x5f, 0x6c, 0x76, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x65, 0x76, 0x6f, 0x4c, 0x76, 0x12, 0x17, 0x0a, 0x07, 0x65, 0x76, 0x6f, 0x5f,
	0x65, 0x78, 0x70, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x65, 0x76, 0x6f, 0x45, 0x78,
	0x70, 0x12, 0x13, 0x0a, 0x05, 0x73, 0x70, 0x5f, 0x66, 0x6c, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x73, 0x70, 0x46, 0x6c, 0x12, 0x1f, 0x0a, 0x0b, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65,
	0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x75, 0x6e, 0x69,
	0x71, 0x75, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x2b, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x34, 0x0a, 0x10, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0e, 0x6c, 0x61, 0x73, 0x74,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x3b,
	0x70, 0x62, 0x67, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_user_item_proto_rawDescOnce sync.Once
	file_pb_user_item_proto_rawDescData = file_pb_user_item_proto_rawDesc
)

func file_pb_user_item_proto_rawDescGZIP() []byte {
	file_pb_user_item_proto_rawDescOnce.Do(func() {
		file_pb_user_item_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_user_item_proto_rawDescData)
	})
	return file_pb_user_item_proto_rawDescData
}

var file_pb_user_item_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pb_user_item_proto_goTypes = []interface{}{
	(*UserItem)(nil),  // 0: user_item
	(*TimeStamp)(nil), // 1: TimeStamp
}
var file_pb_user_item_proto_depIdxs = []int32{
	1, // 0: user_item.create_time:type_name -> TimeStamp
	1, // 1: user_item.last_update_time:type_name -> TimeStamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pb_user_item_proto_init() }
func file_pb_user_item_proto_init() {
	if File_pb_user_item_proto != nil {
		return
	}
	file_pb_TimeStamp_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_pb_user_item_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_user_item_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_user_item_proto_goTypes,
		DependencyIndexes: file_pb_user_item_proto_depIdxs,
		MessageInfos:      file_pb_user_item_proto_msgTypes,
	}.Build()
	File_pb_user_item_proto = out.File
	file_pb_user_item_proto_rawDesc = nil
	file_pb_user_item_proto_goTypes = nil
	file_pb_user_item_proto_depIdxs = nil
}
