Mode: 1
ProtoFolder: "../example/pb"
FromDatabase:
  Host: "192.168.0.41"
  Port: 3306
  DbName: "demo"
  User: "db_user"
  Password: "password"
FromTable: "PostMessage"
ToDatabase:
  Host: "192.168.0.41"
  Port: 3306
  DbName: "demo"
  User: "db_user"
  Password: "password"
ToTable: "PostMessage"
Generate: true
Print: true
Sync: true